name: 'Arbor - Theme recipe'
description: 'Configures Arbor theme and dependent modules and UI Bootstrap base theme.'
type: 'Site'
install:
  # Core.
  - help
  # Contrib.
  - arbor
  - block_class
  - ds
  - ds_extras
  - field_group
  - layout_discovery
  - layout_options
  - sdc_display
  - twig_tweak
  - ui_icons
  - ui_icons_backport
  - ui_icons_field
  - ui_icons_picker
  - ui_patterns
  - ui_patterns_field_formatters
  - ui_patterns_layouts
  - ui_patterns_library
  - ui_skins
  - ui_styles
  - ui_suite_bootstrap
config:
  strict: false
  import:
    # Only Display suite has config.
    ds: "*"
    # Import theme blocks.
    arbor:
      - block.block.arbor_branding
      - block.block.arbor_breadcrumbs
      - block.block.arbor_content
      - block.block.arbor_footer
      - block.block.arbor_help
      - block.block.arbor_local_actions
      - block.block.arbor_local_tasks
      - block.block.arbor_main_menu
      - block.block.arbor_messages
      - block.block.arbor_page_title
  actions:
    # Allow Display Suite on fields and Layouts.
    ds.settings:
      simpleConfigUpdate:
        field_template: true
        ft-layout-builder: true
    # Set the default theme.
    system.theme:
      simpleConfigUpdate:
        default: arbor
    # Allow anonymous users to access patterns page.
    user.role.anonymous:
      grantPermission: 'access patterns page'
